# Generated by Django 5.0.6 on 2024-07-08 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFT',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=255)),
                ('bot', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'user_ft',
            },
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
