# Generated by Django 5.0.6 on 2024-07-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_userft_delete_message'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userft',
            table='user_dt',
        ),
    ]
